model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  # target: taming.models.vqgan.VQNoDiscModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256 #output from encoder
      resolution: 320 #height, width of input
      in_channels: 1 #no color
      out_ch: 1 #no color
      ch: 128 #starting channels (128, 320, 320)
      # ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      # ch_mult: [1, 1, 2, 4, 8] #(128, 128, 256, 512, 1024)
                                #resolution 320, 160, 80, 40, 20
      ch_mult: [1, 1, 2, 2, 4]
      # num_res_blocks: 2
      num_res_blocks: 1
      attn_resolutions: [20] #downsample by 2 each time for len(ch_mult)-1 times
      dropout: 0.1
      resamp_with_conv: True

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        # disc_start: 10000
        disc_start: 5000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 32
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /data/scratch/ellen660/taming-transformers/dataset/shhs2/breathing_train.txt
        size: 1200 
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /data/scratch/ellen660/taming-transformers/dataset/shhs2/breathing_test.txt
        size: 1200

